### ISSUE TITLE
No module named 'regions.core'; 'regions' is not a package

### ISSUE THREAD

**Issue by rasputin1917** [astropy/regions#253] opened 2019-04-08 16:36 UTC
Hi, I got the following message when I tried to import regions like that:

`from regions.core import PixCoord`
`from regions.shapes.circle import CirclePixelRegion`
`center = PixCoord(x, y)`
`reg = CirclePixelRegion(center, 1.0)`

`Traceback (most recent call last):
  File "/"...".py", line 11, in <module> from regions.core import PixCoord
ImportError: No module named 'regions.core'; 'regions' is not a package`
and
`    from regions.shapes.circle import CirclePixelRegion                  
ImportError: No module named 'regions.shapes'; 'regions' is not a package`

_I ran the test:_

running test
installing to temporary directory: /tmp/regions-test-avppgsct
warning: no files found matching 'README.rst'
warning: no files found matching 'ez_setup.py'
warning: no files found matching '*' under directory 'licenses'
warning: no files found matching '*' under directory 'cextern'
warning: no files found matching '*' under directory 'scripts'
no previously-included directories found matching 'build'
no previously-included directories found matching 'docs/_build'
no previously-included directories found matching 'docs/api'
warning: no previously-included files matching '*.o' found anywhere in distribution
=================== test session starts =======================
platform linux -- Python 3.5.2, pytest-4.1.1, py-1.7.0, pluggy-0.8.1

Running tests with regions version 0.4.dev882.
Running tests in regions docs.

Full Python Version: 
3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.15.4
Scipy: 1.2.0
Matplotlib: 3.0.2
Cython: 0.29.6
Astropy: 3.1.1
Astropy-healpix: 0.4
astropy_helpers: 2.0.9
Using Astropy options: remote_data: none.

rootdir: /tmp/regions-test-avppgsct/lib/python3.5/site-packages, inifile: setup.cfg
plugins: remotedata-0.3.1, openfiles-0.3.2, doctestplus-0.2.0, arraydiff-0.3
collected 945 items                                                                                                                                                                                        

regions/_geometry/tests/test_circular_overlap_grid.py ......................................................                                                                                         [  5%]
regions/_geometry/tests/test_elliptical_overlap_grid.py ............................................................................................................................................ [ 20%]
.................................................................................................................................................................................................... [ 41%]
......................................................................................................................................................                                               [ 57%]
regions/_geometry/tests/test_rectangular_overlap_grid.py .................................................................................                                                           [ 65%]
regions/_utils/tests/test_examples.py .....                                                                                                                                                          [ 66%]
regions/core/tests/test_bounding_box.py ..........                                                                                                                                                   [ 67%]
regions/core/tests/test_compound.py ..                                                                                                                                                               [ 67%]
regions/core/tests/test_mask.py ............                                                                                                                                                         [ 68%]
regions/core/tests/test_pixcoord.py ...........                                                                                                                                                      [ 69%]
regions/io/crtf/tests/test_crtf_language.py ........                                                                                                                                                 [ 70%]
regions/io/ds9/tests/test_ds9_language.py ........................                                                                                                                                   [ 73%]
regions/io/fits/tests/test_fits_region.py ....                                                                                                                                                       [ 73%]
regions/io/tests/test_shape_object.py .....                                                                                                                                                          [ 74%]
regions/shapes/tests/test_annulus.py .....s.............s.............s........                                                                                                                      [ 78%]
regions/shapes/tests/test_api.py ............s...............xx....xx.x..x..xxxxx........................................                                                                            [ 88%]
regions/shapes/tests/test_circle.py ..............                                                                                                                                                   [ 89%]
regions/shapes/tests/test_ellipse.py ..............                                                                                                                                                  [ 91%]
regions/shapes/tests/test_line.py ...s.........                                                                                                                                                      [ 92%]
regions/shapes/tests/test_masks.py ...........x....x...                                                                                                                                              [ 94%]
regions/shapes/tests/test_point.py ...s........                                                                                                                                                      [ 95%]
regions/shapes/tests/test_polygon.py ..s............                                                                                                                                                 [ 97%]
regions/shapes/tests/test_rectangle.py ..............                                                                                                                                                [ 98%]
regions/shapes/tests/test_text.py ...s.......                                                                                                                                                        [100%]

========================== 924 passed, 8 skipped, 13 xfailed in 59.11 seconds ==============

======= warnings summary ===============================
../lib/python3.5/site-packages/regions/io/ds9/tests/test_ds9_language.py::test_read
  ../lib/python3.5/site-packages/regions/io/ds9/read.py:283: DS9RegionParserWarning: Region type 'panda' was identified, but it is not one of the known region types.
    warn(msg, DS9RegionParserWarning)
  ../lib/python3.5/site-packages/regions/io/ds9/read.py:283: DS9RegionParserWarning: Region type 'panda' was identified, but it is not one of the known region types.
    warn(msg, DS9RegionParserWarning)
  ..v/lib/python3.5/site-packages/regions/io/ds9/read.py:283: DS9RegionParserWarning: Region type 'panda' was identified, but it is not one of the known region types.
    warn(msg, DS9RegionParserWarning)
..v/lib/python3.5/site-packages/regions/io/ds9/read.py:283: DS9RegionParserWarning: Region type 'panda' was identified, but it is not one of the known region types.
    warn(msg, DS9RegionParserWarning)
  ../lib/python3.5/site-packages/regions/io/ds9/read.py:283: DS9RegionParserWarning: Region type 'panda' was identified, but it is not one of the known region types.
  warn(msg, DS9RegionParserWarning)
 ../lib/python3.5/site-packages/regions/io/core.py:92: DS9RegionParserWarning: Skipping elliptical annulus Shape
  Type : reg
  Coord sys : fk5
  Region type : ellipse
  Meta: OrderedDict([('color', 'red'), ('dashlist', '8 3'), ('width', '3'), ('font', 'helvetica'), ('select', '1'), ('highlite', '1'), ('dash', '0'), ('fixed', '0'), ('edit', '1'), ('move', '1'), ('delete', '1'), ('include', True), ('source', '1'), ('text', 'Ellipse Annulus'), ('fontsize', '10'), ('fontstyle', 'bold'), ('fontweight', 'roman')])
  Composite: False
  Include: True
  
    warn(msg, DS9RegionParserWarning)

...............etc........................

What is that about?? How can I fix this?
Regions is already installed in Pycharm

Thanks in advance

**Comment by keflavich** [comment] 2019-05-15 13:03
I don't know what to make of this; I can't reproduce the error and no one else has reported it.  

How are you running the tests?  It looks like they were successful

**Comment by cdeil** [comment] 2019-05-16 16:56
@rasputin1917 - You have an error "regions is not a package", i.e. you have an installation issue.

You should just `pip install` or `conda install` the regions package as mentioned here:
https://astropy-regions.readthedocs.io/en/latest/installation.html

Then importing regions should work:
```
$ python
...
>>> import regions
```

---

Did you git clone or download the development version of `regions`?
That's only advisable when you want to hack on this package, not when you want to use it.

---

I'll close this issue for now.

But if you still have questions, please comment here again or go on the Astropy Slack ( https://www.astropy.org/help.html ) where you get a reply more quickly concerning installation issues.

**Closed by cdeil** 2019-05-16 16:56 UTC
Labels: question
