### ISSUE TITLE
conda install fails on travis-ci with Python 3.6

### ISSUE THREAD

**Issue by cdeil** [astropy/regions#112] opened 2017-02-16 13:30 UTC
@bsipocz - The Python 3.6 builds on travis-ci are failing with a conda install fail:
https://travis-ci.org/astropy/regions/jobs/202159396
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - astropy
  - numpy 1.12*
  - python 3.6*
```

This is just a CI issue, so I'll still cut the 0.2 release now.
(just mentioning it so that you don't commit to master, but go through a pull request to fix this CI issue)

**Comment by bsipocz** [comment] 2017-02-16 13:44
Yes, this is annoying and I'm figuring out a workaround today as others reported this, too. Too bad that conda updates their package list so slow this time, numpy 1.12 was released a month ago.

**Comment by cdeil** [comment] 2017-02-16 13:51
Well, probably there are zero issues with 3.6 that aren't covered by testing with 3.5.

So my suggestion would be that you just deactivate the Python 3.6 entries from the build matrix and in a month or two, when the issue has resolved itself, re-activate them.

**Comment by bsipocz** [comment] 2017-02-16 13:53
The issue is not with 3.6, but with numpy 1.2, as there is no build for this combination yet. There will be one on conda-forge, soon, but that won't help us in most of the packages. 
I'll add a workaround into ci-helpers later today, so install astropy from pip in this case, but that's an ugly hack so I'll wait a bit longer in case someone has a better idea...

**Comment by cdeil** [comment] 2017-02-19 16:05
We're now getting a similar (the same?) error in Gammapy with Python 3.5 also:
https://travis-ci.org/gammapy/gammapy/jobs/202965853

Is there any way to fix or work around this conda install issue?
The Gammapy coding sprint in Paris  🇫🇷 starts tomorrow.
cc @adonath

**Comment by bsipocz** [comment] 2017-02-19 20:27
@cdeil - The regions one should already work (astropy 1.3 + np1.12). 

The gammapy one you get is due to the missing photutils version. I'll look that issue tonight, and will try to build the missing conda packages (have an idea for working around the current conda issue). I'll ping you once it's done. If nothing else works then I would suggest to temporarily use pip for photutils.

**Comment by bsipocz** [comment] 2017-02-20 01:16
@cdeil - Unfortunately I don't think I can do much about this until the 1.12 builds became available on the defaults channel (e.g. https://travis-ci.org/bsipocz/gammapy/jobs/203288932, that has that only change on top of the branch you linked above). As a workaround I would though suggest to add ``conda-forge`` to ``CONDA_CHANNELS``, so ``conda install photutils`` will see the astropy builds from there (somehow having astropy installed from pip is not good enough to it).

**Comment by bsipocz** [comment] 2017-02-20 09:29
closing this issue as regions is all green now.

**Closed by bsipocz** 2017-02-20 09:29 UTC
Labels: bug, testing
